name: test
on:
  - push
  - pull_request
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node-version:
          - 14.17.0
          - 16.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run tests
        run: npm test
        env:
          GCS_KEY: ${{ secrets.GCS_KEY }}
          GCS_PROJECT_ID: ${{ secrets.GCS_PROJECT_ID }}
          GCS_BUCKET: drive-gcs
          GCS_NO_UNIFORM_ACL_BUCKET: drive-gcs-no-uniform-acl
  windows:
    runs-on: windows-latest
    needs: linux
    strategy:
      max-parallel: 1
      matrix:
        node-version:
          - 14.17.0
          - 16.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run tests
        run: npm test
        env:
          GCS_KEY: ${{ secrets.GCS_KEY }}
          GCS_PROJECT_ID: ${{ secrets.GCS_PROJECT_ID }}
          GCS_BUCKET: drive-gcs
          GCS_NO_UNIFORM_ACL_BUCKET: drive-gcs-no-uniform-acl
